name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Extract version from tag
      id: extract_version
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          # 移除 refs/tags/ 前缀
          TAG_NAME=${GITHUB_REF#refs/tags/}
          # 如果标签以 v 开头，移除 v 前缀
          if [[ "${TAG_NAME}" == v* ]]; then
            VERSION=${TAG_NAME#v}
          else
            VERSION=${TAG_NAME}
          fi
        else
          VERSION="1.0.0-preview.$(date +%Y%m%d%H%M%S)"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
          9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./artifacts -p:PackageVersion=${{ steps.extract_version.outputs.version }}
      
    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET }} --source https://api.nuget.org/v3/index.json --skip-duplicate 